# Generated by Django 5.2.5 on 2025-08-26 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField(help_text='A short bio about yourself')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('twitter_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('demo_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('source_code_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies used', max_length=200)),
                ('completion_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Higher number appears first')),
            ],
            options={
                'ordering': ['-display_order', '-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('other', 'Other')], default='other', max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(help_text='Proficiency level from 1-100%', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', '-proficiency', 'name'],
            },
        ),
    ]
