# Generated by Django 5.2.5 on 2025-08-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Describe the challenges faced during the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='Describe the solution implemented to overcome the challenges.'),
        ),
    ]
