# Generated by Django 5.2.5 on 2025-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_challenges_project_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_document',
            field=models.FileField(blank=True, help_text='PDF document related to the project', null=True, upload_to='projects/documents/'),
        ),
    ]
