# Generated by Django 5.2.5 on 2025-08-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_project_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_document',
        ),
    ]
