# Generated by Django 5.2.5 on 2025-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_project_project_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('development', 'In Development'), ('planning', 'Planning Phase')], default='development', max_length=20),
        ),
    ]
